version: "3"

services:
  httpd:
    image: "httpd:alpine"
    volumes:
      - type: bind
        source: htdocs
        target: /usr/local/apache2/htdocs/
      - type: bind
        source: conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: cert
        target: /usr/local/apache2/conf/server.crt
      - type: bind
        source: key
        target: /usr/local/apache2/conf/server.key
    ports:
      - "80:80"
    restart: "on-failure:5"

volumes:
  htdocs: ./htdocs/
  conf: ./httpd.conf
  cert: ./server.crt
  key: ./server.key
