config:
  node_agent: 'docker-compose'
  deploy_template: '.sqa/docker-compose.yml'
  project_repos:
    worsica-processing:
      repo: 'https://github.com/WORSICA/worsica-processing.git'
      branch: master
      dockerhub: worsica/worsica-processing
      dockertag: latest
    worsica-intermediate:
      repo: 'https://github.com/WORSICA/worsica-intermediate.git'
      branch: master
      dockerhub: worsica/worsica-intermediate
      dockertag: latest
    worsica-portal:
      repo: 'https://github.com/WORSICA/worsica-portal.git'
      branch: master
      dockerhub: worsica/worsica-portal
      dockertag: latest
    worsica-cicd:
      repo: 'https://github.com/WORSICA/worsica-cicd.git'
      branch: master
      dockerhub: worsica/worsica-cicd
      dockertag: latest

sqa-criteria:
  qc-style:
    repos:
      worsica-processing:
        container: processing
        tox:
          testenv: stylecheck
          tox_file: './tox.ini'
  qc-functional:
    repos:
      worsica-processing:
        container: processing
        tox:
          testenv: unittest
          tox_file: './tox.ini'
      worsica-portal:
        container: celery
        tox:
          testenv: functional
          tox_file: './tox.ini'
  qc-coverage:
    repos:
      worsica-processing:
        container: processing
        tox:
          testenv: coverage
          tox_file: './tox.ini'
  qc-security:
    repos:
      worsica-processing:
        container: processing
        tox:
          testenv: security
          tox_file: './tox.ini'
  qc-doc:
    repos:
      worsica-cicd:
        container: processing 
        commands:
          - python setup.py build_sphinx

environment:
  GIT_COMMITTER_NAME: Person1
  GIT_COMMITTER_EMAIL: person1@example.org
  LANG: C.UTF-8

timeout: 600