config:
  node_label: 'worsica.vo.incd.pt'
  node_workspace: './worsica.vo.incd.pt'
  node_agent: 'docker-compose'
  dockerfile: '.sqa/docker-compose.yml'
  project_repos:
    - 'https://github.com/WORSICA/worsica-processing.git'
    - 'https://github.com/WORSICA/worsica-intermediate.git'
    - 'https://github.com/WORSICA/worsica-portal.git'
  dockerhub_repos:
    - 'worsica/worsica-cicd'

sqa-criteria:
  qc-style:
    container: processing
    tox:
      testenv: stylecheck
  qc-functional:
    container: processing
    tox:
      testenv: unittest
  qc-coverage:
    container: processing
    tox:
      testenv: coverage
  qc-security:
    container: processing
    tox:
      testenv: security
  qc-doc:
    container: processing
    commands:
      - python setup.py build_sphinx

environment:
  TOX_FILE: './tox.ini'
  GIT_COMMITTER_NAME: Person1
  GIT_COMMITTER_EMAIL: person1@example.org
  LANG: C.UTF-8

timeout: 600