version: "3"

services:
  essentials:
    build:
      context: "."
      dockerfile: "./docker_essentials/aio_v4/Dockerfile.essentials"
    image: "worsica/jenkins-worsica-essentials:${GIT_BRANCH}"

  intermediate:
    build:
      context: "./worsica-intermediate"
      dockerfile: "./docker_intermediate/aio_v4/Dockerfile.intermediate"
      cache_from:
        - "worsica/jenkins-worsica-essentials:${GIT_BRANCH}"
    image: "worsica/jenkins-worsica-intermediate:${GIT_BRANCH}"
    container_name: "intermediate"
    hostname: "intermediate"
    volumes:
     - type: bind
       source: worsica_web_intermediate
       target: /usr/local/worsica_web_intermediate
     - type: bind
       source: worsica_web_products
       target: /usr/local/worsica_web_products
    entrypoint: "/bin/bash"
    command: "/usr/local/worsica_web_intermediate/worsica_runserver.sh"
    depends_on:
      - essentials
      - postgis
      - rabbitmq
    networks:
      - worsica_net

  frontend:
    build:
      context: "./worsica-frontend"
      dockerfile: "./docker_frontend/aio_v4/Dockerfile.frontend"
      cache_from:
        - "worsica/jenkins-worsica-essentials:${GIT_BRANCH}"
    image: "worsica/jenkins-worsica-frontend:${GIT_BRANCH}"
    container_name: "frontend"
    hostname: "frontend"
    volumes:
     - type: bind
       source: worsica_web
       target: /usr/local/worsica_web
     - type: bind
       source: worsica_frontend
       target: /usr/local/worsica_frontend
    entrypoint: "/bin/bash"
    command: "/usr/local/worsica_web/worsica_runserver.sh"
    depends_on:
      - essentials
      - postgis
      - rabbitmq
      - intermediate
    networks:
      - worsica_net

  postgis:
    image: "mdillon/postgis:9.6"
    container_name: "postgis"
    hostname: "postgis"
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - worsica_net
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "LANG=en_US.utf8"
      - "PGDATA=/var/lib/postgresql/data"
    restart: "on-failure:5"

  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: "rabbitmq"
    hostname: "worsica-backend"
    volumes:
        - type: volume
          source: rabbitmq_data
          target: /var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    networks:
      - worsica_net
    environment:
        - "RABBITMQ_DEFAULT_VHOST=corsica_vhost"
        - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
        - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
    restart: "on-failure:5"

volumes:
  worsica_web_intermediate: ./worsica_intermediate/worsica_web_intermediate
  worsica_web: ./worsica_frontend/worsica_web
  worsica_frontend: ./worsica_frontend
  worsica_web_products: ./worsica_processing
  database_data:
  rabbitmq_data:

networks:
  worsica_net:
    ipam:
      driver: default
